const formatVariables = require('../../../utils/formatVariables.cjs');


const colours = {
	background: '#f7f0eb',
	grey: '#606060',
	grey_light: '#bfbfbf',
	brown: '#5f4138',
	maroon: '#6e3f44',
	purple_bright: '#9440a0',
	purple_bright_light: '@purple_bright',
	purple: '#7561c1',
	purple_light: '#b388cc',
	navy: '#364c93',
	navy_light: '@navy',
	blue_mid: '#0067b7',
	blue: '#318ce7',
	blue_light: '#3eccfd',
	teal: '#218e80',
	green_dark: '#275942',
	green: '#64ad66',
	green_light: '#85c335',
	lime: '#bac335',
	red: '#e53f51',
	red_light: '@red',
	pink_dark: '#bd1b4e',
	pink: '#cb5699',
	pink_light: '@pink',
	peach: '#fb8875',
	orange_dark: '#b34e1f',
	orange: '#f78d2b',
	orange_light: '@orange',
	yellow: '#ffce03',
	yellow_light: '@yellow',
	white: '#f5f0f0',
	black: '#0d0d0d',
	neutral: '@black',
	aimhigher: '#009dee',
	amy: '@purple_bright',
	amy_other: '@purple',
	dan: '@teal',
	wedding: '@green_dark',
	crewe_fam: '@green_light',
	kapers_crewe: '@red',
	holidays_birthdays: '@pink_dark',
	makerx: '@pink',
	ddd: '@orange',
	kapernick_fam: '@yellow'
}

module.exports = formatVariables(colours)
