<script lang="ts">
	import type { AuslanSign, SignStatus } from '$types/generated';
	import Card from './Card.svelte';
	import Modal from '$parts/Modal.svelte';
	import StatusSelect from './StatusSelect.svelte';
	import Video from '$img/icons/clapperboard-fill.svg?component';
	import Book from '$img/icons/agenda-bookmark-fill.svg?component';

	const { id, name, status, tip, reference, onStatusChange, class: className = '' }: AuslanSign & { onStatusChange?: (id: string, status: SignStatus) => void; class?: string } = $props();

	const statusLabel: Record<SignStatus, string> = {
		introduce_next: 'Introduce',
		in_progress: 'In Progress',
		signing_occasionally: 'Sometimes',
		recognises: 'Recognises',
		coming_soon: 'Soon',
		done: 'Signing',
	};

	let videoOpen = $state(false);
	let gifFailed = $state(false);
</script>

<Card
	title={name}
	class={className}
>
	<div class="content">
		{#if tip}
			<p class="tip">{tip}</p>
		{/if}
		{#if reference?.note}
			<p class="note">{reference.note}</p>
		{/if}
		{#if onStatusChange}
			<StatusSelect
				class="status"
				{id}
				{status}
				labels={statusLabel}
				onChange={onStatusChange}
			/>
		{:else}
			<span class="status">{statusLabel[status]}</span>
		{/if}
		{#if reference?.video}
			<button
				class="video_link"
				onclick={() => (videoOpen = true)}
			>
				<Video />
				<span class="sr-only">Watch video</span>
			</button>
		{/if}
		{#if reference?.url}
			<!-- eslint-disable-next-line svelte/no-navigation-without-resolve -- reference.url is the external Signbank dictionary page, not an internal route -->
			<a href={reference.url} target="_blank" class="sign_link">
				<span class="sr-only">Signbank page for {name}</span>
				<Book />
			</a>
		{/if}
	</div>
</Card>

{#if reference?.video}
	<Modal
		bind:open={videoOpen}
		title={`${name} - Signbank video`}
	>
		{#if gifFailed}
			<video
				src={reference.video}
				controls
				autoplay
				muted
				loop
				class="video"
			>
				<track kind="captions" />
			</video>
		{:else}
			<!-- Pre-generated by household_api's generate:sign-gifs script; falls back to the
				 live Signbank video above until this sign's gif has been generated. -->
			<img
				src={`/signs/${id}.gif`}
				alt={`Signbank sign for ${name}`}
				class="video"
				onerror={() => (gifFailed = true)}
			/>
		{/if}
	</Modal>
{/if}

<style>
	@import '@mixins';

	.content {
		display: grid;
		grid-template-areas: 'tip tip tip tip' 'note note note note' 'video link . status';
		grid-template-columns: auto auto 1fr auto;
		grid-template-rows: auto 1fr auto;
		height: 100%;

		& :global(.status) {
			grid-area: status;
			align-self: center;
			margin: 0 1ch 0 0;
		}
	}

	.video_link {

		@include button_icon;

		grid-area: video;
		margin-right: 1ch;
	}

	.video {
		max-width: 100%;
		max-height: 70vh;
	}

	.note {
		grid-area: note;
	}

	.tip {
		grid-area: tip;
	}

	.note,
	.tip {
		margin: 0 0 0.7em;
		font-size: 0.9em;
	}

	.sign_link {

		@include button;

		@include button_icon;

		grid-area: link;
		margin-right: 1ch;
	}
</style>
