<script lang="ts">
	import type { AuslanSign, SignStatus } from '$types/generated';
	import Card from '../Card/index.svelte';
	import Modal from '$parts/Modal/index.svelte';
	import StatusSelect from '../StatusSelect/index.svelte';
	import Video from '$img/icons/clapperboard-fill.svg?component';
	import Book from '$img/icons/agenda-bookmark-fill.svg?component';
	import styles from './index.module.css';

	const { id, name, status, tip, reference, onStatusChange, class: className = '' }: AuslanSign & { onStatusChange?: (id: string, status: SignStatus) => void; class?: string } = $props();

	const statusLabel: Record<SignStatus, string> = {
		introduce_next: 'Introduce',
		in_progress: 'In Progress',
		signing_occasionally: 'Sometimes',
		recognises: 'Recognises',
		coming_soon: 'Soon',
		done: 'Signing',
	};

	let videoOpen = $state(false);
	let gifFailed = $state(false);
</script>

<Card
	title={name}
	class={className}
>
	<div class={styles.content}>
		{#if tip}
			<p class={styles.tip}>{tip}</p>
		{/if}
		{#if reference?.note}
			<p class={styles.note}>{reference.note}</p>
		{/if}
		{#if onStatusChange}
			<StatusSelect
				class="status"
				{id}
				{status}
				labels={statusLabel}
				onChange={onStatusChange}
			/>
		{:else}
			<span class="status">{statusLabel[status]}</span>
		{/if}
		{#if reference?.video}
			<button
				class={styles.video_link}
				onclick={() => (videoOpen = true)}
			>
				<Video />
				<span class="sr-only">Watch video</span>
			</button>
		{/if}
		{#if reference?.url}
			<!-- eslint-disable-next-line svelte/no-navigation-without-resolve -- reference.url is the external Signbank dictionary page, not an internal route -->
			<a href={reference.url} target="_blank" class={styles.sign_link}>
				<span class="sr-only">Signbank page for {name}</span>
				<Book />
			</a>
		{/if}
	</div>
</Card>

{#if reference?.video}
	<Modal
		bind:open={videoOpen}
		title={`${name} - Signbank video`}
	>
		{#if gifFailed}
			<video
				src={reference.video}
				controls
				autoplay
				muted
				loop
				class={styles.video}
			>
				<track kind="captions" />
			</video>
		{:else}
			<!-- Pre-generated by household_api's generate:sign-gifs script; falls back to the
				 live Signbank video above until this sign's gif has been generated. -->
			<img
				src={`/signs/${id}.gif`}
				alt={`Signbank sign for ${name}`}
				class={styles.video}
				onerror={() => (gifFailed = true)}
			/>
		{/if}
	</Modal>
{/if}
